Remove scala 2.12 for JS platform
stryker-mutator/weapon-regex pull request #53
Opened 2021-05-17 14:14 UTC by Nhaajt

- Remove scala 2.12 for JS platform since it adds no extra value when converted to JS and only the generated JS code from scala 2.13 is released to `npm` anyway

2021-05-17 14:52 UTC, hugo-vrijswijk requested changes
I'd be against this. As a library, you reasonably want as many people as possible to be able to use your library. This includes supporting somewhat recent versions that many people will still use. Yes, StrykerJS only uses 2.13, but it's very possible that someone will want to integrate Weapon-regeX into their Scala.JS application on 2.12. 

I don't think it's a good idea to only look at what Stryker4s and StrykerJS will use the library for. It's also possible that Stryker4s might do more with Scala.JS in the future, and will need a 2.12 Scala.JS version for it

2021-05-17 15:50 UTC, Nhaajt commented
> I'd be against this. As a library, you reasonably want as many people as possible to be able to use your library. This includes supporting somewhat recent versions that many people will still use. Yes, StrykerJS uses the 2.13 bundle, but it's very possible that someone will want to integrate Weapon-regeX into their Scala.JS application on 2.12.
> 
> I don't think it's a good idea to only look at what Stryker4s and StrykerJS will use the library for. It's also possible that Stryker4s might do more with Scala.JS in the future, and will need a 2.12 Scala.JS version for it. There's not a very high maintenance cost in supporting 2.12, so I'd suggest keeping it until the Scala community moves away from 2.12 (like it's done with 2.11)

If I understand correctly, I only removed scala 2.12 for the JS platform so that the JS code only being generated by 2.13. The library in the JVM platform still get compiled into scala 2.13 and 2.12, so Scala/Scala.JS users can still use the library in both versions. In total, there should be 3 build targets: scala 2.13, scala 2.12, and JS (from 2.13).

2021-05-17 22:00 UTC, hugo-vrijswijk commented
> The library in the JVM platform still get compiled into scala 2.13 and 2.12, so Scala/Scala.JS users can still use the library in both versions

Scala.js users can only use libraries that are compiled against the same Scala version _and_ for the same platform. So anyone wanting to use Weapon Regex with Scala.js would be forced to use 2.13 as it's only published against that. Since it's already being cross-built against 2.12 for the JVM target I think it doesn't make sense to remove 2.12 from Scala.js target. There's no extra maintenance cost, and it can only cause confusion.

E.g.: I want to create an application that uses both Scala and Scala.js. Because of an older library I am still stuck on 2.12. I would be able to use Weapon Regex for the JVM part of my application, but not for the JS part. This is a bit of a confusing restriction from a user perspective

2021-05-18 02:04 UTC, Nhaajt commented
Understood 👌

2021-05-18 02:04 UTC, closed without merging

2021-05-18 07:11 UTC, hugo-vrijswijk commented
Good to have the discussion, though! I never like supporting older versions either 😁. In an ideal world we'd all be on Scala 3 now